name: github-runner-image-builder
base: core22 # the base snap is the execution environment for this snap
version: "0.1" # just for humans, typically '1.2+git' or '1.3.2'
summary: The snap for building images for github-runners
description: |
  Github-runner-image-builder is a snap for building ubuntu images for
  github-runner charm (https://github.com/canonical/github-runner-operator/)
  used by the github-runner-image-builder charm. It periodically builds
  new images according to the configuration.

license: Apache-2.0
grade: stable
confinement: strict
architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

apps:
  github-runner-image-builder:
    command: bin/github-runner-image-builder
    daemon: simple

parts:
  github-runner-image-builder:
    plugin: python
    source: .
    stage-packages:
      - "qemu-utils"
      - "libguestfs-tools"

hooks:
  configure: {}
