name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    name: Integration test
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox
        run: python -m pip install tox-gh>=1.2
        # need to run in sudo mode due to chroot
      - name: Run integration tests
        run: sudo $(which tox) -e integration
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
