name: Integration tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests-arm:
    name: Integration test (ARM64)
    runs-on: [self-hosted, ARM64]
    strategy:
      matrix:
        image: [jammy, noble]
        py: ["3.10.11"] # The only 3.10 version w/ ARM64 support
    steps:
      - uses: actions/checkout@v3
      - uses: canonical/setup-lxd@v0.1.1
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox
        run: |
          sudo apt-get update
          sudo apt-get install pipx -y
          pipx ensurepath
          pipx install tox
      # need to run in sudo mode due to chroot
      - name: Run integration tests
        run: sudo $(which tox) -e integration -- --image=${{ matrix.image }} ${{ secrets.INTEGRATION_TEST_ARGS }}
  
  integration-tests-amd:
    name: Integration test (X64)
    runs-on: [self-hosted, X64]
    strategy:
      matrix:
        image: [jammy, noble]
        py: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: canonical/setup-lxd@v0.1.1
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
      - name: Install tox
        run: |
          sudo apt-get update
          sudo apt-get install pipx -y
          pipx ensurepath
          pipx install tox
      # need to run in sudo mode due to chroot
      - name: Run integration tests
        run: sudo $(which tox) -e integration -- --image=${{ matrix.image }} ${{ secrets.INTEGRATION_TEST_ARGS }}
